### ISSUE TITLE
Get rid of 'contains' for strings

### ISSUE THREAD

**Issue by daschubert** [SiegelDaniel/MQTT-IDS#16]
When executing refining.py in AGL, I get the following error
```
AttributeError: 'str' object has no attribute 'contains'
```
This might result from a different string encoding compared to the testing environment.
Using `in` or `find` should be more robust.

**Comment by SiegelDaniel** [comment]
I could not find any occurence of a string.contains.
If the error is reproducible, could you provide me with information on which exact line throws that error?

**Comment by daschubert** [comment]
https://github.com/SiegelDaniel/MQTT-IDS/blob/4443dd8590bd48ffa288485523dde0f7bbc34cbf/src/refining.py#L97

**Comment by SiegelDaniel** [comment]
Thanks, will fix

daschubert <notifications@github.com> schrieb am Fr., 15. März 2019, 16:25:

**Comment by daschubert** [comment]
Reopen because this is not fixed in master.
https://github.com/SiegelDaniel/MQTT-IDS/blob/29f0786895f6a71968d0a5757014584d4a73b3d8/src/refining.py#L97

We can close this, when the corresponding branch is merged or the problem is temporarily fixed for master.
