### ISSUE TITLE
No messages on "ANOMALY"

### ISSUE THREAD

**Issue by daschubert** [SiegelDaniel/MQTT-IDS#27]
Using an empty DB file, I don't get messages on the "ANOMALY" topic, although [processing.py](https://github.com/SiegelDaniel/MQTT-IDS/blob/b6b65accfa3700d7b0e183eb79d65ac3aa513325/src/processing.py) is receiving traces.

**Comment by SiegelDaniel** [comment]
Fixed in 3517a036aefd414b5f343272500468630961801e

![grafik](https://user-images.githubusercontent.com/14983741/55681546-d1cd4c80-5927-11e9-82f6-9a9d2b1b0c68.png)

Ready for further testing
