### ISSUE TITLE
Use psutil to get pid by process name

### ISSUE THREAD

**Issue by daschubert** [SiegelDaniel/MQTT-IDS#28]
Because of licensing issues we have to move to psutil to get the pid of processes.

**Comment by SiegelDaniel** [comment]
Implemented in 67be5e4e9cf54112f10e149bcaf2f8228f86b039, ready for test

**Comment by daschubert** [comment]
Should be fixed in 64c6e86957621e6cadfb35eb278f4cd6ba3bc318
Needs still to be tested on AGL
