### ISSUE TITLE
Finalize README

### ISSUE THREAD

**Issue by daschubert** [SiegelDaniel/MQTT-IDS#29]
Last thing to be done before this project is added to [Eclipse Kuksa](https://www.eclipse.org/kuksa/).

**Comment by SiegelDaniel** [comment]
See 3a89f9d8bf8bd774502295cc1f66f52a6fbd2aa8.
Reopen if necessary.

**Comment by daschubert** [comment]
I'm still working on it. Latest version is in master with #34. However, this is not final.

**Comment by daschubert** [comment]
Done with #51
