### ISSUE TITLE
Adapt to "Full sequence" STIDE variant

### ISSUE THREAD

**Issue by daschubert** [SiegelDaniel/MQTT-IDS#35]
This comprises 2 tasks:
1. Use the sliding window approach to store systemcall sequences.
2. Anomalies are those sequences that cannot be found in the database.

See:
- Stephanie Forrest, Steven Hofmeyr, and Anil Somayaji. Computer immunology. Communications of the ACM, 40(10):88–96, October 1997.

- Steven A. Hofmeyr, Stephanie Forrest, and Anil Somayaji. Intrusion detection using sequences of system calls. Journal of Computer Security, 6(3), 1998

**Comment by SiegelDaniel** [comment]
Changed to sliding window in 32d0468f1d366c1b95c73ccbe715763f1bf62154.

**Comment by SiegelDaniel** [comment]
Anomalies are sequences that cannot be found in the database as of 90bdc2582d059dbfaa75ab95227a8f5e53926ffa
