### ISSUE TITLE
First entry in database seems to be broken

### ISSUE THREAD

**Issue by daschubert** [SiegelDaniel/MQTT-IDS#36]
As an example:

| Trace 0  | Trace 1 | Trace 2 |
| ------------- | ------------- | ------------- |
| Process 2450 attached  | restart_syscall  | recvmsg |

**Comment by SiegelDaniel** [comment]
Reimplemented quick and dirty fix in f639d2d9b16529c8a67ce460e91e6983e6cad66d

**Comment by SiegelDaniel** [comment]
Works now. Tested successfully on Ubuntu x64
fef0c550c31c56c03b6df9e98cd4ebfca93f7f1b
