### ISSUE TITLE
Don't use instance variables as arguments when calling functions of the corresponding object

### ISSUE THREAD

**Issue by daschubert** [SiegelDaniel/MQTT-IDS#39]
An example for this:
https://github.com/SiegelDaniel/MQTT-IDS/blob/23a55b882aa78399e2a121378bc7dec2e8db9ef6/src/syscall_tracer.py#L56-L57

Remove the instance variable or the parameter ;)

**Comment by SiegelDaniel** [comment]
Fixed in: a997a2010ff78e969093aa74003e14b1bcc90d15

**Comment by SiegelDaniel** [comment]
Forgot one:
1c393a6ac3f3fb6bf34ce79fb9bf57c85f5bec7d

**Comment by daschubert** [comment]
Done with #45
